steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', '$REPO_NAME', '--image=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '--allow-unauthenticated', '--platform=managed' , '--region=us-east1']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=southamerica-east1-a'
